### ISSUE TITLE
[build]

### ISSUE THREAD

**Issue by adnanagbaria** [clang-ykt/ONNF#37]
Hello,

I tried to build the project with "cmake --build . --target onnf". However, I got a compilation errors at frontend_dialect_transformer.cpp:170, 171, 497, 553, 600
" no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrField<onnx::TensorShapeProto_Dimension>’ and ‘int’)
         int dim_numeric_size = shape_proto.dim()[i].dim_value();"

I'm running on Ubuntu with python3.
Maybe I miss something?

Thanks!
Adnan

**Comment by tjingrant** [comment]
This is a likely a protobuf version issue. What version of protobuf are you using?
You can run 
```
protoc --version
```
and copy&paste the result here.

**Comment by adnanagbaria** [comment]
libprotoc 3.0.0

What version shall we use?

**Comment by adnanagbaria** [comment]
Updated to libprotoc 3.6.1
But, did not work! Still have the compilation errors!

**Comment by adnanagbaria** [comment]
In the generated makefile, the linkage has the following:
$(CC) -g  -rdynamic -lz ...

This will cause a problem such as: libz.so: error adding symbols: DSO missing from command line
I'd recommend to move '-lz' to the end to solve the problem

**Comment by tjingrant** [comment]
Hi @adnanagbaria thanks for the feedback, did upgrading to 3.6.1 at least solve the problem you described regarding:
```
" no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrFieldonnx::TensorShapeProto_Dimension’ and ‘int’)
```

Regarding the issue with linking with zlib, the -lz flag is currently a hard-coded link flag. I've updated our build script to let CMake determine how to link with zlib: https://github.com/clang-ykt/ONNF/pull/40/files. If you can let me know your thought, that'd be wonderful because I wasn't able to reproduce this problem on my machine & the buildbot...

**Comment by adnanagbaria** [comment]
looks good!
