### ISSUE TITLE
Add prerequisites for building ONNF

### ISSUE THREAD

**Issue by doru1004** [clang-ykt/ONNF#85]
@tjingrant I have added a small list of pre-requisites for ONNF. Please check it and see if it's missing anything.

**Comment by tjingrant** [comment]
It seems to be fairly reasonable to me. Thanks for keeping a working copy of llvm-project! I wonder if we should default to using this version of llvm-project in our buildbot and decide when to sync ourselves.

Apart from that, we may want to avoid editing files in the master branch directly so as to 1). help reviewer locate the diff set. 2). we want to keep master branch commit history clean and concise so that when we cut a release, we can simply use commit history as changelog. 

Directly editing the README.md does not leave a nice trail in our master branch commit history - 
![image](https://user-images.githubusercontent.com/6410074/74588207-74208b00-5035-11ea-99b0-15a1d0ed8de3.png)

**Comment by doru1004** [comment]
There don't seem to be any more prerequisites so closing this issue.
